<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Restaurant;
use App\Models\User;
use App\Models\Campus;

class RestaurantSeeder extends Seeder
{
    public function run(): void
    {
        $user = User::where('role', 'user')->first();
        $campuses = Campus::all();

        if (!$user || $campuses->isEmpty()) {
            return;
        }

        $restaurants = [
            [
                'user_id' => $user->id,
                'campus_id' => $campuses->where('name', 'Universitas Pendidikan Indonesia')->first()?->id ?? $campuses->first()->id,
                'name' => 'Ayam Geprek UPI Mantap',
                'category' => 'makanan_berat',
                'is_featured' => true,
                'food_type' => 'Ayam Geprek',
                'image' => 'restaurants/placeholder.jpg',
                'description' => 'Ayam geprek super pedas dengan berbagai pilihan level cabai, sangat populer di kalangan mahasiswa UPI.',
                'address' => 'Jl. Dr. Setiabudi No.229, Sukasari, Bandung',
                'open_hours' => '10:00 - 21:00',
                'price_range' => 'Rp 15.000 - Rp 25.000',
                'gmaps_link' => 'https://maps.google.com',
                'latitude' => -6.8612,
                'longitude' => 107.5888,
                'landmark' => 'Gerbang Utama UPI',
                'landmark_photo' => 'default.png',
                'status' => 'approved',
                'rating' => 4.5,
            ],
            [
                'user_id' => $user->id,
                'campus_id' => $campuses->where('name', 'Institut Teknologi Bandung')->first()?->id ?? $campuses->first()->id,
                'name' => 'Nasi Goreng Ganesha ITB',
                'category' => 'makanan_berat',
                'food_type' => 'Nasi Goreng',
                'image' => 'restaurants/placeholder.jpg',
                'description' => 'Nasi goreng legendaris dengan porsi melimpah dan aroma khas arang tungku.',
                'address' => 'Jl. Ganesha No.10, Lb. Siliwangi, Coblong, Bandung',
                'open_hours' => '17:00 - 23:00',
                'price_range' => 'Rp 18.000 - Rp 30.000',
                'gmaps_link' => 'https://maps.google.com',
                'latitude' => -6.8944,
                'longitude' => 107.6106,
                'landmark' => 'Kantin Masjid Salman ITB',
                'landmark_photo' => 'default.png',
                'status' => 'approved',
                'rating' => 4.8,
            ],
            [
                'user_id' => $user->id,
                'campus_id' => $campuses->where('name', 'Universitas Padjajaran')->first()?->id ?? $campuses->first()->id,
                'name' => 'Sate Jatinangor Unpad',
                'category' => 'makanan_berat',
                'food_type' => 'Sate Ayam',
                'image' => 'restaurants/placeholder.jpg',
                'description' => 'Sate ayam bumbu kacang kental khas Madura, dagingnya tebal dan empuk.',
                'address' => 'Jl. Raya Bandung Sumedang KM.21, Jatinangor',
                'open_hours' => '16:00 - 22:00',
                'price_range' => 'Rp 20.000 - Rp 35.000',
                'gmaps_link' => 'https://maps.google.com',
                'latitude' => -6.9218,
                'longitude' => 107.7697,
                'landmark' => 'Dekat Gerbang Unpad Jatinangor',
                'landmark_photo' => 'default.png',
                'status' => 'approved',
                'rating' => 4.2,
            ],
            [
                'user_id' => $user->id,
                'campus_id' => $campuses->where('name', 'Telkom University')->first()?->id ?? $campuses->first()->id,
                'name' => 'Warkop Cozy Tel-U',
                'category' => 'minuman',
                'food_type' => 'Kopi & Indomie',
                'image' => 'restaurants/placeholder.jpg',
                'description' => 'Tempat nongkrong asyik dengan wifi cepat, menyediakan aneka kopi, mie instan kekinian, dan jajanan ringan.',
                'address' => 'Jl. Telekomunikasi No.1, Terusan Buah Batu, Bandung',
                'open_hours' => '24 Jam',
                'price_range' => 'Rp 5.000 - Rp 20.000',
                'gmaps_link' => 'https://maps.google.com',
                'latitude' => -6.9732,
                'longitude' => 107.6301,
                'landmark' => 'Gedung Tokong Nanas',
                'landmark_photo' => 'default.png',
                'status' => 'approved',
                'rating' => 4.0,
            ],
            [
                'user_id' => $user->id,
                'campus_id' => $campuses->where('name', 'Universitas Parahyangan')->first()?->id ?? $campuses->first()->id,
                'name' => 'Batagor Ciumbuleuit Unpar',
                'category' => 'jajanan',
                'food_type' => 'Batagor',
                'image' => 'restaurants/placeholder.jpg',
                'description' => 'Batagor renyah dengan rasa tenggiri premium dan saus kacang gurih pedas manis.',
                'address' => 'Jl. Ciumbuleuit No.94, Hegarmanah, Cidadap, Bandung',
                'open_hours' => '09:00 - 18:00',
                'price_range' => 'Rp 10.000 - Rp 20.000',
                'gmaps_link' => 'https://maps.google.com',
                'latitude' => -6.8746,
                'longitude' => 107.6075,
                'landmark' => 'Seberang Kampus Unpar',
                'landmark_photo' => 'default.png',
                'status' => 'approved',
                'rating' => 4.7,
            ],
            [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Universitas Pendidikan Indonesia')->first()?->id ?? $campuses->first()->id,
        'name' => 'Ayam Geprek Gacor Gang Kujang',
        'category' => 'makanan_berat',
        'is_featured' => true,
        'food_type' => 'Ayam Geprek, Nasi Putih',
        'image' => 'default.png',
        'description' => 'Hidden gem sejati anak UPI. Tempatnya nyempil di dalam gang tapi ayam gepreknya juara dan porsi nasinya kuli banget.',
        'address' => 'Jl. Kujang, Geger Kalong, Bandung',
        'open_hours' => '09:00 - 21:00',
        'price_range' => 'Rp 10.000 - Rp 15.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyUPI1',
        'latitude' => -6.860410,
        'longitude' => 107.590010,
        'landmark' => 'Masuk gang sebelah fotokopian, warung cat hijau',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.8,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Universitas Pendidikan Indonesia')->first()?->id ?? $campuses->first()->id,
        'name' => 'Seblak Prasmanan Teh Nining',
        'category' => 'jajanan',
        'is_featured' => false,
        'food_type' => 'Seblak, Kerupuk, Baso, Sosis',
        'image' => 'default.png',
        'description' => 'Pilihan toppingnya super banyak dan kuah kencurnya medok. Surganya pecinta pedas di sekitar kampus.',
        'address' => 'Jl. Setiabudi Lorong 3, Bandung',
        'open_hours' => '10:00 - 20:00',
        'price_range' => 'Rp 8.000 - Rp 20.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyUPI2',
        'latitude' => -6.861100,
        'longitude' => 107.591200,
        'landmark' => 'Samping kosan warna biru',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.6,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Universitas Pendidikan Indonesia')->first()?->id ?? $campuses->first()->id,
        'name' => 'Es Coklat Tambah Umur',
        'category' => 'minuman',
        'is_featured' => false,
        'food_type' => 'Es Coklat, Roti Bakar',
        'image' => 'default.png',
        'description' => 'Minuman penyelamat dahaga abis nugas. Coklatnya kental dan harganya bener-bener gak bikin kantong bolong.',
        'address' => 'Jl. Geger Kalong Girang',
        'open_hours' => '11:00 - 19:00',
        'price_range' => 'Rp 5.000 - Rp 12.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyUPI3',
        'latitude' => -6.862300,
        'longitude' => 107.592500,
        'landmark' => 'Depan lapangan basket warga',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.7,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Universitas Pendidikan Indonesia')->first()?->id ?? $campuses->first()->id,
        'name' => 'Nasi Kuning Pagi Malam',
        'category' => 'makanan_berat',
        'is_featured' => false,
        'food_type' => 'Nasi Kuning, Telur Balado',
        'image' => 'default.png',
        'description' => 'Penyelamat lapar tengah malam. Nasi kuningnya wangi dan sambalnya pedas manis nagih.',
        'address' => 'Jl. Dr. Setiabudi No.200',
        'open_hours' => '18:00 - 02:00',
        'price_range' => 'Rp 10.000 - Rp 15.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyUPI4',
        'latitude' => -6.863400,
        'longitude' => 107.593100,
        'landmark' => 'Gerobak dekat pertigaan jalan utama',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.5,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Universitas Pendidikan Indonesia')->first()?->id ?? $campuses->first()->id,
        'name' => 'Cireng Bumbu Rujak Mang Asep',
        'category' => 'jajanan',
        'is_featured' => false,
        'food_type' => 'Cireng Goreng, Bumbu Rujak',
        'image' => 'default.png',
        'description' => 'Cireng crispy di luar kenyal di dalam, bumbu rujaknya kental dan pedas segar.',
        'address' => 'Jl. Gegerkalong Tengah',
        'open_hours' => '14:00 - 21:00',
        'price_range' => 'Rp 5.000 - Rp 10.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyUPI5',
        'latitude' => -6.864100,
        'longitude' => 107.594000,
        'landmark' => 'Sebelah minimarket Koperasi',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.4,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Universitas Pendidikan Indonesia')->first()?->id ?? $campuses->first()->id,
        'name' => 'Warkop Aa Setiabudi',
        'category' => 'makanan_berat',
        'is_featured' => false,
        'food_type' => 'Indomie, Roti Bakar, Kopi',
        'image' => 'default.png',
        'description' => 'Tempat nongkrong 24 jam. Bumbu rahasia indomienya bikin rasanya beda dari warkop biasa.',
        'address' => 'Jl. Setiabudi Gang 4',
        'open_hours' => '00:00 - 23:59',
        'price_range' => 'Rp 7.000 - Rp 15.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyUPI6',
        'latitude' => -6.865200,
        'longitude' => 107.595100,
        'landmark' => 'Samping gapura desa',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.5,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Universitas Pendidikan Indonesia')->first()?->id ?? $campuses->first()->id,
        'name' => 'Mie Ayam Mas No',
        'category' => 'makanan_berat',
        'is_featured' => false,
        'food_type' => 'Mie Ayam, Baso Urat',
        'image' => 'default.png',
        'description' => 'Potongan ayamnya besar-besar, kuah kaldunya gurih. Selalu habis sebelum jam 5 sore.',
        'address' => 'Gegerkalong Wetan',
        'open_hours' => '09:00 - 17:00',
        'price_range' => 'Rp 12.000 - Rp 18.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyUPI7',
        'latitude' => -6.866300,
        'longitude' => 107.596200,
        'landmark' => 'Depan kos-kosan putri',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.6,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Universitas Pendidikan Indonesia')->first()?->id ?? $campuses->first()->id,
        'name' => 'Batagor Kering Khas Ledeng',
        'category' => 'jajanan',
        'is_featured' => true,
        'food_type' => 'Batagor, Siomay',
        'image' => 'default.png',
        'description' => 'Batagor legendaris yang sembunyi di teras rumah. Bumbu kacangnya pekat dan ikannya terasa.',
        'address' => 'Jl. Ledeng Dalam',
        'open_hours' => '12:00 - 20:00',
        'price_range' => 'Rp 10.000 - Rp 15.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyUPI8',
        'latitude' => -6.867400,
        'longitude' => 107.597300,
        'landmark' => 'Teras rumah warga nomor 12',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.8,
    ],

    // ================= UNPAD =================
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Universitas Padjadjaran')->first()?->id ?? $campuses->first()->id,
        'name' => 'Dimsum Tenda DU',
        'category' => 'jajanan',
        'is_featured' => true,
        'food_type' => 'Dimsum Ayam, Nori, Mentai',
        'image' => 'default.png',
        'description' => 'Jajanan malam wajib kalau lagi main ke Dipatiukur. Chili oil-nya nendang banget.',
        'address' => 'Jl. Dipatiukur No. 80',
        'open_hours' => '17:00 - 23:00',
        'price_range' => 'Rp 13.000 - Rp 20.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyUNPAD1',
        'latitude' => -6.890600,
        'longitude' => 107.615800,
        'landmark' => 'Sebelah halte Dipatiukur',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.7,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Universitas Padjadjaran')->first()?->id ?? $campuses->first()->id,
        'name' => 'Nasi Padang Uda Leman',
        'category' => 'makanan_berat',
        'is_featured' => false,
        'food_type' => 'Nasi Rames, Rendang, Ayam Pop',
        'image' => 'default.png',
        'description' => 'Bumbu rendangnya otentik dan harganya jauh lebih miring dibanding restoran padang jalan raya.',
        'address' => 'Jl. Sekeloa No.5',
        'open_hours' => '08:00 - 21:00',
        'price_range' => 'Rp 12.000 - Rp 25.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyUNPAD2',
        'latitude' => -6.889500,
        'longitude' => 107.614700,
        'landmark' => 'Masuk jalan kecil seberang monumen',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.5,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Universitas Padjadjaran')->first()?->id ?? $campuses->first()->id,
        'name' => 'Kopi Susu Sudut Kampus',
        'category' => 'minuman',
        'is_featured' => false,
        'food_type' => 'Kopi Susu Gula Aren',
        'image' => 'default.png',
        'description' => 'Hidden kedai kopi yang rasanya gak kalah sama brand besar. Cocok buat nemenin nugas.',
        'address' => 'Jl. Teuku Umar Dalam',
        'open_hours' => '08:00 - 22:00',
        'price_range' => 'Rp 10.000 - Rp 15.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyUNPAD3',
        'latitude' => -6.888400,
        'longitude' => 107.613600,
        'landmark' => 'Kios kecil samping laundry',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.6,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Universitas Padjadjaran')->first()?->id ?? $campuses->first()->id,
        'name' => 'Sate Taichan Sekeloa',
        'category' => 'makanan_berat',
        'is_featured' => true,
        'food_type' => 'Sate Taichan, Lontong',
        'image' => 'default.png',
        'description' => 'Dagingnya juicy dan sambalnya ekstra pedas. Selalu ramai antrean mahasiswa.',
        'address' => 'Jl. Sekeloa Tengah',
        'open_hours' => '18:00 - 23:30',
        'price_range' => 'Rp 15.000 - Rp 25.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyUNPAD4',
        'latitude' => -6.887300,
        'longitude' => 107.612500,
        'landmark' => 'Depan Alfamart Sekeloa',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.8,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Universitas Padjadjaran')->first()?->id ?? $campuses->first()->id,
        'name' => 'Kue Balok Lumer Mang Didin',
        'category' => 'jajanan',
        'is_featured' => false,
        'food_type' => 'Kue Balok Coklat Lumer',
        'image' => 'default.png',
        'description' => 'Dimasak pakai arang, coklatnya benar-benar lumer di mulut saat disajikan panas.',
        'address' => 'Jl. Dipatiukur (Dekat SPBU)',
        'open_hours' => '16:00 - 00:00',
        'price_range' => 'Rp 3.000 - Rp 15.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyUNPAD5',
        'latitude' => -6.886200,
        'longitude' => 107.611400,
        'landmark' => 'Gerobak tenda kuning',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.7,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Universitas Padjadjaran')->first()?->id ?? $campuses->first()->id,
        'name' => 'Jus Buah Jumbo 10K',
        'category' => 'minuman',
        'is_featured' => false,
        'food_type' => 'Aneka Jus Buah Segar',
        'image' => 'default.png',
        'description' => 'Porsi gelas super besar, buahnya asli dan gak pelit. Seger banget buat siang bolong.',
        'address' => 'Jl. Hasanudin No.12',
        'open_hours' => '09:00 - 20:00',
        'price_range' => 'Rp 10.000 - Rp 15.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyUNPAD6',
        'latitude' => -6.885100,
        'longitude' => 107.610300,
        'landmark' => 'Kios warna hijau',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.4,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Universitas Padjadjaran')->first()?->id ?? $campuses->first()->id,
        'name' => 'Ayam Penyet Sambal Ijo',
        'category' => 'makanan_berat',
        'is_featured' => false,
        'food_type' => 'Ayam Penyet, Tahu, Tempe',
        'image' => 'default.png',
        'description' => 'Nyempil di ujung gang, tapi rasa sambal ijonya bikin rela balik lagi.',
        'address' => 'Jl. Tubagus Ismail Bawah',
        'open_hours' => '10:00 - 21:00',
        'price_range' => 'Rp 13.000 - Rp 18.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyUNPAD7',
        'latitude' => -6.884000,
        'longitude' => 107.609200,
        'landmark' => 'Ujung gang buntu',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.5,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Universitas Padjadjaran')->first()?->id ?? $campuses->first()->id,
        'name' => 'Tahu Crispy Bumbu Tabur',
        'category' => 'jajanan',
        'is_featured' => false,
        'food_type' => 'Tahu Goreng Crispy',
        'image' => 'default.png',
        'description' => 'Cemilan keriuk yang bumbunya pas banget, gak bikin gatal di tenggorokan.',
        'address' => 'Jl. Dipatiukur (Depan gerbang kampus)',
        'open_hours' => '13:00 - 22:00',
        'price_range' => 'Rp 5.000 - Rp 10.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyUNPAD8',
        'latitude' => -6.882900,
        'longitude' => 107.608100,
        'landmark' => 'Gerobak depan indomaret',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.3,
    ],

    // ================= ITB =================
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Institut Teknologi Bandung')->first()?->id ?? $campuses->first()->id,
        'name' => 'Ayam Guling Salman',
        'category' => 'makanan_berat',
        'is_featured' => true,
        'food_type' => 'Ayam Guling, Nasi Panas',
        'image' => 'default.png',
        'description' => 'Ayam guling legendaris yang manis gurihnya meresap sampai ke tulang. Menu andalan anak ITB.',
        'address' => 'Jl. Ganesa No.7, Lb. Siliwangi',
        'open_hours' => '08:00 - 16:00',
        'price_range' => 'Rp 15.000 - Rp 25.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyITB1',
        'latitude' => -6.891500,
        'longitude' => 107.610600,
        'landmark' => 'Kantin di dalam area Salman',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.9,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Institut Teknologi Bandung')->first()?->id ?? $campuses->first()->id,
        'name' => 'Nasi Campur Gelap Nyawang',
        'category' => 'makanan_berat',
        'is_featured' => false,
        'food_type' => 'Nasi Campur Prasmanan',
        'image' => 'default.png',
        'description' => 'Penyelamat lapar setelah praktikum malam. Lauknya beragam dan harganya sangat bersahabat.',
        'address' => 'Jl. Gelap Nyawang',
        'open_hours' => '17:00 - 23:00',
        'price_range' => 'Rp 10.000 - Rp 20.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyITB2',
        'latitude' => -6.892600,
        'longitude' => 107.611700,
        'landmark' => 'Tenda deretan paling ujung',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.6,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Institut Teknologi Bandung')->first()?->id ?? $campuses->first()->id,
        'name' => 'Susu Murni Ijan Gelap Nyawang',
        'category' => 'minuman',
        'is_featured' => false,
        'food_type' => 'Susu Murni Rasa-rasa',
        'image' => 'default.png',
        'description' => 'Tempat nongkrong asik sambil minum susu hangat di dinginnya malam Bandung.',
        'address' => 'Jl. Gelap Nyawang No. 2',
        'open_hours' => '18:00 - 00:00',
        'price_range' => 'Rp 6.000 - Rp 12.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyITB3',
        'latitude' => -6.893700,
        'longitude' => 107.612800,
        'landmark' => 'Samping tukang sate',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.5,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Institut Teknologi Bandung')->first()?->id ?? $campuses->first()->id,
        'name' => 'Seblak Ganesha',
        'category' => 'jajanan',
        'is_featured' => true,
        'food_type' => 'Seblak Tulang, Kerupuk Mawar',
        'image' => 'default.png',
        'description' => 'Kuahnya merah merona dan rasanya sangat pedas gurih. Favorit banget pas lagi hujan.',
        'address' => 'Jl. Ganesa Lorong 1',
        'open_hours' => '11:00 - 19:00',
        'price_range' => 'Rp 10.000 - Rp 18.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyITB4',
        'latitude' => -6.894800,
        'longitude' => 107.613900,
        'landmark' => 'Masuk gang depan gerbang utama',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.7,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Institut Teknologi Bandung')->first()?->id ?? $campuses->first()->id,
        'name' => 'Mie Ayam Pangsit Ceker',
        'category' => 'makanan_berat',
        'is_featured' => false,
        'food_type' => 'Mie Ayam, Ceker Manis',
        'image' => 'default.png',
        'description' => 'Tekstur mienya kenyal dan cekernya super lembut sampai tulangnya bisa dikunyah.',
        'address' => 'Jl. Ganesa (Samping Gerbang)',
        'open_hours' => '09:00 - 16:00',
        'price_range' => 'Rp 12.000 - Rp 17.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyITB5',
        'latitude' => -6.895900,
        'longitude' => 107.615000,
        'landmark' => 'Gerobak mangkal depan pagar kampus',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.4,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Institut Teknologi Bandung')->first()?->id ?? $campuses->first()->id,
        'name' => 'Es Krim Pot Taman Hutan',
        'category' => 'jajanan',
        'is_featured' => false,
        'food_type' => 'Es Krim Cone & Cup',
        'image' => 'default.png',
        'description' => 'Es krim jadul yang harganya murah meriah. Pas buat healing sejenak habis kelas.',
        'address' => 'Area Taman Sabuga ITB',
        'open_hours' => '10:00 - 17:00',
        'price_range' => 'Rp 5.000 - Rp 15.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyITB6',
        'latitude' => -6.897000,
        'longitude' => 107.616100,
        'landmark' => 'Taman dekat hutan kota',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.5,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Institut Teknologi Bandung')->first()?->id ?? $campuses->first()->id,
        'name' => 'Kopi Seduh Sepeda',
        'category' => 'minuman',
        'is_featured' => false,
        'food_type' => 'Kopi Hitam, Kopi Susu',
        'image' => 'default.png',
        'description' => 'Kopi seduh manual pakai sepeda. Rasanya premium tapi harga mahasiswa bgt.',
        'address' => 'Area Kampus ITB Ganesa',
        'open_hours' => '07:00 - 15:00',
        'price_range' => 'Rp 5.000 - Rp 10.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyITB7',
        'latitude' => -6.898100,
        'longitude' => 107.617200,
        'landmark' => 'Keliling sekitar parkiran sepeda',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.6,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Institut Teknologi Bandung')->first()?->id ?? $campuses->first()->id,
        'name' => 'Tongseng Sapi Kang Maman',
        'category' => 'makanan_berat',
        'is_featured' => false,
        'food_type' => 'Tongseng Sapi, Sate',
        'image' => 'default.png',
        'description' => 'Daging sapinya empuk banget dan kuahnya rich rempah. Sering sold out jam 8 malam.',
        'address' => 'Jl. Ir. H. Juanda (Dekat Ganesa)',
        'open_hours' => '16:00 - 22:00',
        'price_range' => 'Rp 18.000 - Rp 25.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyITB8',
        'latitude' => -6.899200,
        'longitude' => 107.618300,
        'landmark' => 'Sebelah pertigaan Dago',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.8,
    ],

    // ================= UNPAR =================
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Universitas Katolik Parahyangan')->first()?->id ?? $campuses->first()->id,
        'name' => 'Nasi Cikur Mang Ucup',
        'category' => 'makanan_berat',
        'is_featured' => true,
        'food_type' => 'Nasi Cikur, Telur Dadar',
        'image' => 'default.png',
        'description' => 'Aroma kencur (cikur) nya wangi banget. Sarapan paling mantap sebelum kuliah pagi di Ciumbuleuit.',
        'address' => 'Jl. Ciumbuleuit No.25',
        'open_hours' => '07:00 - 14:00',
        'price_range' => 'Rp 10.000 - Rp 15.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyUNPAR1',
        'latitude' => -6.873500,
        'longitude' => 107.604600,
        'landmark' => 'Teras rumah nomor 25',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.7,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Universitas Katolik Parahyangan')->first()?->id ?? $campuses->first()->id,
        'name' => 'Sate Maranggi Ciumbuleuit',
        'category' => 'makanan_berat',
        'is_featured' => false,
        'food_type' => 'Sate Sapi, Ketan Bakar',
        'image' => 'default.png',
        'description' => 'Satenya empuk dan bumbu kecap pedasnya nagih. Nyempil dikit dari jalan raya tapi worth it.',
        'address' => 'Jl. Ciumbuleuit Atas',
        'open_hours' => '16:00 - 23:00',
        'price_range' => 'Rp 20.000 - Rp 30.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyUNPAR2',
        'latitude' => -6.874600,
        'longitude' => 107.605700,
        'landmark' => 'Seberang minimarket Yomart',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.6,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Universitas Katolik Parahyangan')->first()?->id ?? $campuses->first()->id,
        'name' => 'Es Kopi Teras Belakang',
        'category' => 'minuman',
        'is_featured' => false,
        'food_type' => 'Kopi Susu, Matcha',
        'image' => 'default.png',
        'description' => 'Kedai kopi rahasia di belakang area kampus. Tenang banget buat ngerjain skripsi.',
        'address' => 'Jl. Ciumbuleuit Gang Mawar',
        'open_hours' => '09:00 - 20:00',
        'price_range' => 'Rp 12.000 - Rp 18.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyUNPAR3',
        'latitude' => -6.875700,
        'longitude' => 107.606800,
        'landmark' => 'Masuk lewat parkiran motor',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.8,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Universitas Katolik Parahyangan')->first()?->id ?? $campuses->first()->id,
        'name' => 'Lumpia Basah Bumbu Kacang',
        'category' => 'jajanan',
        'is_featured' => true,
        'food_type' => 'Lumpia Basah, Bengkuang',
        'image' => 'default.png',
        'description' => 'Porsinya tebal dan bumbu kacangnya berasa banget. Jajanan wajib sore hari.',
        'address' => 'Jl. Ciumbuleuit Depan Kampus',
        'open_hours' => '12:00 - 18:00',
        'price_range' => 'Rp 8.000 - Rp 12.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyUNPAR4',
        'latitude' => -6.876800,
        'longitude' => 107.607900,
        'landmark' => 'Samping gerbang utara',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.5,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Universitas Katolik Parahyangan')->first()?->id ?? $campuses->first()->id,
        'name' => 'Bakso Cuanki Jalanan',
        'category' => 'makanan_berat',
        'is_featured' => false,
        'food_type' => 'Bakso, Cuanki Siomay',
        'image' => 'default.png',
        'description' => 'Kuah kaldu ikannya terasa beda. Enak banget dimakan pas cuaca Ciumbuleuit lagi dingin.',
        'address' => 'Jl. Punclut Bawah',
        'open_hours' => '13:00 - 21:00',
        'price_range' => 'Rp 15.000 - Rp 20.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyUNPAR5',
        'latitude' => -6.877900,
        'longitude' => 107.609000,
        'landmark' => 'Pikulan mangkal dekat tikungan',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.4,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Universitas Katolik Parahyangan')->first()?->id ?? $campuses->first()->id,
        'name' => 'Makaroni Pedas Gila',
        'category' => 'jajanan',
        'is_featured' => false,
        'food_type' => 'Makaroni Kering, Basah',
        'image' => 'default.png',
        'description' => 'Bisa request tingkat kepedasan dari level 1 sampai nangis. Bumbu jagung bakarnya favorit.',
        'address' => 'Jl. Ciumbuleuit Tengah',
        'open_hours' => '10:00 - 19:00',
        'price_range' => 'Rp 5.000 - Rp 10.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyUNPAR6',
        'latitude' => -6.879000,
        'longitude' => 107.610100,
        'landmark' => 'Stand kecil sebelah ruko fotokopi',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.3,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Universitas Katolik Parahyangan')->first()?->id ?? $campuses->first()->id,
        'name' => 'Es Campur Segar Bugar',
        'category' => 'minuman',
        'is_featured' => false,
        'food_type' => 'Es Campur, Es Oyen',
        'image' => 'default.png',
        'description' => 'Isiannya melimpah ruah, ada kelapa muda, alpukat, dan nangka yang wangi.',
        'address' => 'Jl. Ranggamalela',
        'open_hours' => '11:00 - 17:00',
        'price_range' => 'Rp 10.000 - Rp 15.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyUNPAR7',
        'latitude' => -6.880100,
        'longitude' => 107.611200,
        'landmark' => 'Di bawah pohon rindang seberang kost',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.5,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Universitas Katolik Parahyangan')->first()?->id ?? $campuses->first()->id,
        'name' => 'Nasi Goreng Bistik AA',
        'category' => 'makanan_berat',
        'is_featured' => false,
        'food_type' => 'Nasi Goreng, Bistik Ayam',
        'image' => 'default.png',
        'description' => 'Nasi gorengnya wangi smokey wok-hei, ditambah bistik ayam yang crispy dan saus gurih manis.',
        'address' => 'Jl. Ciumbuleuit Raya',
        'open_hours' => '17:00 - 01:00',
        'price_range' => 'Rp 18.000 - Rp 25.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyUNPAR8',
        'latitude' => -6.881200,
        'longitude' => 107.612300,
        'landmark' => 'Tenda pinggir jalan raya',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.7,
    ],

    // ================= UPI Cibiru (Update Koordinat Sekitar Kampus) =================
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'UPI Cibiru')->first()?->id ?? $campuses->first()->id,
        'name' => 'Seblak Jebred Cibiru',
        'category' => 'jajanan',
        'is_featured' => true,
        'food_type' => 'Seblak Kwetiau, Tulang, Ceker',
        'image' => 'default.png',
        'description' => 'Seblak ter-hidden gem di area Cibiru, harganya merakyat dan kuahnya kental rempah kencur banget.',
        'address' => 'Jl. Pendidikan, Cibiru, Bandung',
        'open_hours' => '11:00 - 20:00',
        'price_range' => 'Rp 9.000 - Rp 15.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyCIBIRU1',
        'latitude' => -6.939800,
        'longitude' => 107.723500,
        'landmark' => 'Masuk gang depan gerbang kampus UPI',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.8,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'UPI Cibiru')->first()?->id ?? $campuses->first()->id,
        'name' => 'Ayam Geprek Gila Porsi',
        'category' => 'makanan_berat',
        'is_featured' => false,
        'food_type' => 'Nasi Ayam Geprek, Tahu',
        'image' => 'default.png',
        'description' => 'Bisa nambah nasi sepuasnya! Cocok banget buat anak kosan di akhir bulan.',
        'address' => 'Jl. Manisi No. 10, Cibiru',
        'open_hours' => '09:00 - 21:00',
        'price_range' => 'Rp 12.000 - Rp 18.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyCIBIRU2',
        'latitude' => -6.939500, 
        'longitude' => 107.723800,
        'landmark' => 'Sebelah kosan cat kuning',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.6,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'UPI Cibiru')->first()?->id ?? $campuses->first()->id,
        'name' => 'Es Teh Manis Jumbo Cibiru',
        'category' => 'minuman',
        'is_featured' => false,
        'food_type' => 'Es Teh Kampul, Lemon Tea',
        'image' => 'default.png',
        'description' => 'Cuma 3 ribu dapet teh porsi jumbo rasa otentik yang gak nyangkut di leher.',
        'address' => 'Jl. Pendidikan Dalam',
        'open_hours' => '09:00 - 21:00',
        'price_range' => 'Rp 3.000 - Rp 8.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyCIBIRU3',
        'latitude' => -6.940200, 
        'longitude' => 107.723200,
        'landmark' => 'Gerobak depan ruko fotokopi',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.5,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'UPI Cibiru')->first()?->id ?? $campuses->first()->id,
        'name' => 'Nasi Goreng Rempah Cibiru',
        'category' => 'makanan_berat',
        'is_featured' => false,
        'food_type' => 'Nasi Goreng Kare, Mie Goreng',
        'image' => 'default.png',
        'description' => 'Nasi gorengnya pakai bumbu rempah kuning rahasia. Rasanya beda dari nasgor tek-tek biasa.',
        'address' => 'Jl. Desa Cipadung',
        'open_hours' => '17:00 - 23:59',
        'price_range' => 'Rp 13.000 - Rp 20.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyCIBIRU4',
        'latitude' => -6.940500, // Area permukiman sekitar
        'longitude' => 107.724100,
        'landmark' => 'Depan lapangan bulu tangkis',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.7,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'UPI Cibiru')->first()?->id ?? $campuses->first()->id,
        'name' => 'Basreng Daun Jeruk Melimpah',
        'category' => 'jajanan',
        'is_featured' => false,
        'food_type' => 'Baso Goreng Pedas',
        'image' => 'default.png',
        'description' => 'Basrengnya digoreng dadakan, wangi daun jeruknya sangat pekat dan menggugah selera.',
        'address' => 'Jl. Raya Cibiru Gg. 2',
        'open_hours' => '10:00 - 18:00',
        'price_range' => 'Rp 5.000 - Rp 15.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyCIBIRU5',
        'latitude' => -6.939200, // Dekat arah Pandanwangi
        'longitude' => 107.724500,
        'landmark' => 'Kios kecil samping warteg',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.5,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'UPI Cibiru')->first()?->id ?? $campuses->first()->id,
        'name' => 'Kopi Rumahan Cibiru',
        'category' => 'minuman',
        'is_featured' => true,
        'food_type' => 'Kopi Tubruk, Kopi Susu',
        'image' => 'default.png',
        'description' => 'Kedai di garasi rumah warga. Sunyi, tenang, dan harga kopinya sangat bersahabat.',
        'address' => 'Jl. Cilengkrang 1',
        'open_hours' => '15:00 - 22:00',
        'price_range' => 'Rp 8.000 - Rp 15.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyCIBIRU6',
        'latitude' => -6.938900, // Sedikit ke utara
        'longitude' => 107.723000,
        'landmark' => 'Garasi rumah berpagar hitam',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.8,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'UPI Cibiru')->first()?->id ?? $campuses->first()->id,
        'name' => 'Mie Bakso Mas Kijo',
        'category' => 'makanan_berat',
        'is_featured' => false,
        'food_type' => 'Bakso Urat, Mie Yamin',
        'image' => 'default.png',
        'description' => 'Mie yamin manisnya juara, ditambah bakso urat yang dagingnya kerasa banget.',
        'address' => 'Jl. Sindang Reret Cibiru',
        'open_hours' => '10:00 - 21:00',
        'price_range' => 'Rp 12.000 - Rp 18.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyCIBIRU7',
        'latitude' => -6.940800, // Sedikit ke selatan
        'longitude' => 107.724800,
        'landmark' => 'Sebelah pangkalan ojek',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.6,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'UPI Cibiru')->first()?->id ?? $campuses->first()->id,
        'name' => 'Martabak Mini Unyu',
        'category' => 'jajanan',
        'is_featured' => false,
        'food_type' => 'Martabak Manis Mini',
        'image' => 'default.png',
        'description' => 'Camilan malam manis dengan harga receh. Topping kejunya melimpah sampai tumpah.',
        'address' => 'Jl. Manisi Raya',
        'open_hours' => '16:00 - 22:00',
        'price_range' => 'Rp 2.000 - Rp 10.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyCIBIRU8',
        'latitude' => -6.938500, // Dekat arah area padat penduduk
        'longitude' => 107.722500,
        'landmark' => 'Gerobak depan ruko kosong',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.4,
    ],

    // ================= Tel-U =================
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Telkom University')->first()?->id ?? $campuses->first()->id,
        'name' => 'Nasi Telur Sentosa Sukabirus',
        'category' => 'makanan_berat',
        'is_featured' => true,
        'food_type' => 'Nasi Telur Pontianak',
        'image' => 'default.png',
        'description' => 'Telur dadarnya digoreng garing pinggirnya dengan kuah kecap spesial. Menu wajib tanggal tua.',
        'address' => 'Jl. Sukabirus, Dayeuhkolot',
        'open_hours' => '08:00 - 20:00',
        'price_range' => 'Rp 10.000 - Rp 15.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyTELU1',
        'latitude' => -6.974000,
        'longitude' => 107.630300,
        'landmark' => 'Masuk gang area Sukabirus',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.9,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Telkom University')->first()?->id ?? $campuses->first()->id,
        'name' => 'Ayam Penyet Cabe Hijau PGA',
        'category' => 'makanan_berat',
        'is_featured' => false,
        'food_type' => 'Ayam Penyet, Kol Goreng',
        'image' => 'default.png',
        'description' => 'Sambal cabe hijaunya bikin keringat bercucuran tapi nagih. Plus kol gorengnya super garing.',
        'address' => 'Jl. PGA, Lengkong, Bojongsoang',
        'open_hours' => '10:00 - 22:00',
        'price_range' => 'Rp 14.000 - Rp 20.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyTELU2',
        'latitude' => -6.975100,
        'longitude' => 107.631400,
        'landmark' => 'Di deretan ruko PGA',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.7,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Telkom University')->first()?->id ?? $campuses->first()->id,
        'name' => 'Kopi Kosan Sukapura',
        'category' => 'minuman',
        'is_featured' => false,
        'food_type' => 'Es Kopi Susu Krimi',
        'image' => 'default.png',
        'description' => 'Hidden gem di bawah kos-kosan. Kopinya creamy dan pas banget buat begadang ngerjain tugas koding.',
        'address' => 'Jl. Sukapura, Dayeuhkolot',
        'open_hours' => '10:00 - 23:00',
        'price_range' => 'Rp 12.000 - Rp 18.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyTELU3',
        'latitude' => -6.976200,
        'longitude' => 107.632500,
        'landmark' => 'Di lantai 1 kosan warna putih',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.8,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Telkom University')->first()?->id ?? $campuses->first()->id,
        'name' => 'Seblak Jeletot Ciumbuleuit Telkom',
        'category' => 'jajanan',
        'is_featured' => true,
        'food_type' => 'Seblak Macaroni, Sosis, Telur',
        'image' => 'default.png',
        'description' => 'Bumbunya kental kemerahan, pedasnya menusuk lidah tapi bikin gak bisa berhenti makan.',
        'address' => 'Jl. Raya Bojongsoang',
        'open_hours' => '12:00 - 21:00',
        'price_range' => 'Rp 10.000 - Rp 18.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyTELU4',
        'latitude' => -6.977300,
        'longitude' => 107.633600,
        'landmark' => 'Tenda pinggir jalan raya Bojongsoang',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.6,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Telkom University')->first()?->id ?? $campuses->first()->id,
        'name' => 'Warteg Barokah Jaya',
        'category' => 'makanan_berat',
        'is_featured' => false,
        'food_type' => 'Nasi Rames, Tempe Orek',
        'image' => 'default.png',
        'description' => 'Andalan utama akhir bulan. Sayur, lauk dan nasi porsi besar dengan harga miring banget.',
        'address' => 'Jl. Telekomunikasi, Terusan Buah Batu',
        'open_hours' => '06:00 - 21:00',
        'price_range' => 'Rp 10.000 - Rp 15.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyTELU5',
        'latitude' => -6.978400,
        'longitude' => 107.634700,
        'landmark' => 'Pertigaan menuju gerbang asrama',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.5,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Telkom University')->first()?->id ?? $campuses->first()->id,
        'name' => 'Tahu Bulat Digoreng Dadakan',
        'category' => 'jajanan',
        'is_featured' => false,
        'food_type' => 'Tahu Bulat, Sotong',
        'image' => 'default.png',
        'description' => 'Sering lewat depan kosan sore-sore. Bumbu baladonya tebel dan tahunya kopong gurih.',
        'address' => 'Area Keliling Sukabirus & Sukapura',
        'open_hours' => '15:00 - 22:00',
        'price_range' => 'Rp 5.000 - Rp 10.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyTELU6',
        'latitude' => -6.979500,
        'longitude' => 107.635800,
        'landmark' => 'Mobil pickup keliling area Sukabirus',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.3,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Telkom University')->first()?->id ?? $campuses->first()->id,
        'name' => 'Jus Buah Segar Koding',
        'category' => 'minuman',
        'is_featured' => false,
        'food_type' => 'Jus Alpukat, Jus Mangga',
        'image' => 'default.png',
        'description' => 'Jusnya kental gak banyak air, manisnya pas pake gula asli. Bikin melek lagi sehabis kelas.',
        'address' => 'Jl. Sukabirus Gang 2',
        'open_hours' => '10:00 - 20:00',
        'price_range' => 'Rp 8.000 - Rp 12.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyTELU7',
        'latitude' => -6.980600,
        'longitude' => 107.636900,
        'landmark' => 'Kios dekat pintu keluar motor',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.6,
    ],
    [
        'user_id' => $user->id,
        'campus_id' => $campuses->where('name', 'Telkom University')->first()?->id ?? $campuses->first()->id,
        'name' => 'Sate Padang Ajo Telkom',
        'category' => 'makanan_berat',
        'is_featured' => false,
        'food_type' => 'Sate Padang, Ketupat',
        'image' => 'default.png',
        'description' => 'Kuah kentalnya kuning rempah bgt, ditambah keripik singkong pedas makin mantap dimakan malam hari.',
        'address' => 'Jl. PGA Raya Bojongsoang',
        'open_hours' => '17:00 - 23:00',
        'price_range' => 'Rp 15.000 - Rp 25.000',
        'gmaps_link' => 'https://maps.app.goo.gl/dummyTELU8',
        'latitude' => -6.981700,
        'longitude' => 107.638000,
        'landmark' => 'Tenda kuning di pertigaan PGA',
        'landmark_photo' => null,
        'status' => 'approved',
        'rating' => 4.7,
    ],
];

        foreach ($restaurants as $restaurant) {
            Restaurant::create($restaurant);
        }
    }
}
